# Generated by Django 4.2.10 on 2024-04-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=500)),
                ('Roll_number', models.BigIntegerField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
